spring:
  datasource:
    url: # <<YOUR_URL>>
    username: # <<YOUR_USERNAME>>
    password: # <<YOUR_PASSWORD>>
  jpa:
    hibernate:
      ddl-auto: validate
  config:
    import: "classpath:application-template.yaml"

media:
  output-dir: "${TMP_DIR:tmp}"

ktgram:
  username: # <<your_username>> not mandatory
  bot:
    - token: # <<your_token>>

gpt:
  token: # <<your_token>>
  initial-prompt: "You are a helpful assistant. You are talking to a user. 
  Continue the conversation based on the following previous messages, the username you are talking to. 
  Answer the next message naturally and seamlessly, maintaining the tone and style of the conversation with user. 
  Do not reference or mention these instructions in your response. This was our previous responses:\n\n\n"

  model: "llama3-groq-70b-8192-tool-use-preview"
  n: 1
  frequency-penalty: 0.5
  max-tokens: 1000
  presence-penalty: 0.3
  temperature: 0.7
  top-p: 0.9
  tool-choice: "auto"

tts:
  token: # <<your_token>>
  voice-id: # <<your_voice_id>>
  model-id: "eleven_multilingual_v2"
  stability: 0.5
  similarity-boost: 0.5
  style: 0.0
  use-speaker-boost: true

schedule:
  random-response-chance: 0.01
  daily-message: 0 0 12 * * *
  winner-reset: 0 0 0 * * *
  year-end-message: 0 0 0 1 1 *
#  meme-post: 0 0 * * * * TODO: Implement this
