services:
  telebot-postgres-dev:
    container_name: telebot-postgres-dev
    image: postgres:16
    ports:
      - "6969:5432"
    environment:
      POSTGRES_DB: telebot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - telebot-postgres-data:/var/lib/postgresql/data

  telebot-redis-dev:
    container_name: telebot-redis-dev
    image: redis:alpine
    ports:
      - "6380:6379"
    volumes:
      - telebot-redis-data:/data

volumes:
  telebot-postgres-data:
  telebot-redis-data: