services:
  telegram-bot:
    container_name: telebot
    # build image locally first
    image: tkozakas/telebot:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://telebot-postgres:5432/telebot"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
      BOT_USERNAME: "<<bot_username>>"
      BOT_TOKEN: "<<bot_token>>"
    volumes:
      - ./data:/app/data
    restart: always

  telebot-postgres:
    container_name: telebot-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telebot
    volumes:
      - ./postgres:/var/lib/postgresql/data
    restart: always
